name: Validate Monorepo

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    name: Node ${{ matrix.node }}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout Master
        run: git branch -f master origin/master

      - name: Sanity Check
        run: |
          echo branch `git branch --show-current`;
          echo node `node -v`;
          echo yarn `yarn -v`

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Initliaze .npmrc
        run: echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.OPENBASE_NPM_TOKEN }}\n$(cat .npmrc)" > .npmrc
      - run: cat -n .npmrc

      - name: pnpm install
        run: pnpm install

      - name: Build Packages
        run: pnpm build -r

      - name: Lint Monorepo
        run: pnpm lint

      - name: Run Tests
        run: pnpm test --filter "...[origin/master]"
